/* Generated by luce-fiir-2. Do not edit. */
#include <float.h>
#include <limits.h>
#include <stddef.h>
#include <stdint.h>
#include "examples/c_import/temperature.h"

struct __luce_fiir_temperature_record_luce_temperature_range {
    double field_0;
    double field_1;
};

struct __luce_fiir_temperature_record_luce_temperature_reading {
    struct __luce_fiir_temperature_record_luce_temperature_range field_0;
    int64_t field_1;
    _Bool field_2_is_negative;
    uint64_t field_2_magnitude;
    float field_3;
};

static int32_t __luce_fiir_temperature_decode_c_luce_temperature_range(const struct __luce_fiir_temperature_record_luce_temperature_range *source, luce_temperature_range *destination) {
    destination->minimum = (double)source->field_0;
    destination->maximum = (double)source->field_1;
    return INT32_C(1);
}

static int32_t __luce_fiir_temperature_encode_c_luce_temperature_range(struct __luce_fiir_temperature_record_luce_temperature_range *destination, const luce_temperature_range *source) {
    destination->field_0 = source->minimum;
    destination->field_1 = source->maximum;
    return INT32_C(1);
}

static int32_t __luce_fiir_temperature_decode_c_luce_temperature_reading(const struct __luce_fiir_temperature_record_luce_temperature_reading *source, struct luce_temperature_reading *destination) {
    int32_t field_0_status = __luce_fiir_temperature_decode_c_luce_temperature_range(&source->field_0, &destination->range);
    if (field_0_status != INT32_C(1)) return field_0_status;
    if (source->field_1 < -INT64_C(2147483648) || source->field_1 > INT64_C(2147483647)) return INT32_C(0);
    destination->current = (luce_degrees)source->field_1;
    if (source->field_2_is_negative && source->field_2_magnitude == UINT64_C(2)) destination->scale = LUCE_SCALE_CELSIUS;
    else if (!source->field_2_is_negative && source->field_2_magnitude == UINT64_C(42)) destination->scale = LUCE_SCALE_FAHRENHEIT;
    else return INT32_C(2);
    destination->fraction = (luce_half_value)source->field_3;
    return INT32_C(1);
}

static int32_t __luce_fiir_temperature_encode_c_luce_temperature_reading(struct __luce_fiir_temperature_record_luce_temperature_reading *destination, const struct luce_temperature_reading *source) {
    int32_t field_0_status = __luce_fiir_temperature_encode_c_luce_temperature_range(&destination->field_0, &source->range);
    if (field_0_status != INT32_C(1)) return field_0_status;
    destination->field_1 = source->current;
    if (source->scale == LUCE_SCALE_CELSIUS) { destination->field_2_is_negative = 1; destination->field_2_magnitude = UINT64_C(2); }
    else if (source->scale == LUCE_SCALE_FAHRENHEIT) { destination->field_2_is_negative = 0; destination->field_2_magnitude = UINT64_C(42); }
    else return INT32_C(3);
    destination->field_3 = source->fraction;
    return INT32_C(1);
}

_Static_assert(CHAR_BIT * sizeof(int) == 32, "FIIR C int size changed");
_Static_assert(INT_MIN == -INT64_C(2147483648) && INT_MAX == INT64_C(2147483647), "FIIR C int range changed");
_Static_assert(CHAR_BIT * sizeof(luce_degrees) == 32, "FIIR C typedef luce_degrees size changed");
_Static_assert(_Generic(((luce_degrees)0), int: 1, default: 0), "FIIR C typedef luce_degrees target changed");
_Static_assert(CHAR_BIT * sizeof(_Float16) == 16, "FIIR C _Float16 size changed");
_Static_assert(FLT_RADIX == 2 && __FLT16_MANT_DIG__ == 11 && __FLT16_MAX_EXP__ == 16, "FIIR C _Float16 format changed");
_Static_assert(CHAR_BIT * sizeof(luce_half_value) == 16, "FIIR C typedef luce_half_value size changed");
_Static_assert(_Generic(((luce_half_value)0), _Float16: 1, default: 0), "FIIR C typedef luce_half_value target changed");
_Static_assert(CHAR_BIT * sizeof(double) == 64, "FIIR C double size changed");
_Static_assert(FLT_RADIX == 2 && DBL_MANT_DIG == 53 && DBL_MAX_EXP == 1024, "FIIR C double format changed");
_Static_assert(CHAR_BIT * sizeof(luce_temperature_range) == 128, "FIIR C record luce_temperature_range size changed");
_Static_assert(CHAR_BIT * _Alignof(luce_temperature_range) == 64, "FIIR C record luce_temperature_range alignment changed");
_Static_assert(CHAR_BIT * offsetof(luce_temperature_range, minimum) == 0, "FIIR C record luce_temperature_range field minimum offset changed");
_Static_assert(_Generic(((luce_temperature_range *)0)->minimum, double: 1, default: 0), "FIIR C record luce_temperature_range field minimum type changed");
_Static_assert(CHAR_BIT * offsetof(luce_temperature_range, maximum) == 64, "FIIR C record luce_temperature_range field maximum offset changed");
_Static_assert(_Generic(((luce_temperature_range *)0)->maximum, double: 1, default: 0), "FIIR C record luce_temperature_range field maximum type changed");
_Static_assert(_Generic(((luce_temperature_scale)0), enum luce_temperature_scale: 1, default: 0), "FIIR C typedef luce_temperature_scale target changed");
_Static_assert(CHAR_BIT * sizeof(struct luce_temperature_reading) == 256, "FIIR C record luce_temperature_reading size changed");
_Static_assert(CHAR_BIT * _Alignof(struct luce_temperature_reading) == 64, "FIIR C record luce_temperature_reading alignment changed");
_Static_assert(CHAR_BIT * offsetof(struct luce_temperature_reading, range) == 0, "FIIR C record luce_temperature_reading field range offset changed");
_Static_assert(_Generic(((struct luce_temperature_reading *)0)->range, luce_temperature_range: 1, default: 0), "FIIR C record luce_temperature_reading field range type changed");
_Static_assert(CHAR_BIT * offsetof(struct luce_temperature_reading, current) == 128, "FIIR C record luce_temperature_reading field current offset changed");
_Static_assert(_Generic(((struct luce_temperature_reading *)0)->current, luce_degrees: 1, default: 0), "FIIR C record luce_temperature_reading field current type changed");
_Static_assert(CHAR_BIT * offsetof(struct luce_temperature_reading, scale) == 160, "FIIR C record luce_temperature_reading field scale offset changed");
_Static_assert(_Generic(((struct luce_temperature_reading *)0)->scale, luce_temperature_scale: 1, default: 0), "FIIR C record luce_temperature_reading field scale type changed");
_Static_assert(CHAR_BIT * offsetof(struct luce_temperature_reading, fraction) == 192, "FIIR C record luce_temperature_reading field fraction offset changed");
_Static_assert(_Generic(((struct luce_temperature_reading *)0)->fraction, luce_half_value: 1, default: 0), "FIIR C record luce_temperature_reading field fraction type changed");
_Static_assert(_Generic(((luce_temperature_reading *)0), struct luce_temperature_reading *: 1, default: 0), "FIIR C typedef luce_temperature_reading target changed");
_Static_assert(CHAR_BIT * sizeof(long long) == 64, "FIIR C long long size changed");
_Static_assert(LLONG_MIN == INT64_MIN && LLONG_MAX == INT64_MAX, "FIIR C long long range changed");
_Static_assert(CHAR_BIT * sizeof(unsigned long long) == 64, "FIIR C unsigned long long size changed");
_Static_assert(ULLONG_MAX == UINT64_MAX, "FIIR C unsigned long long range changed");
_Static_assert(CHAR_BIT * sizeof(_Bool) == 8, "FIIR C _Bool size changed");
_Static_assert(CHAR_BIT * sizeof(float) == 32, "FIIR C float size changed");
_Static_assert(FLT_RADIX == 2 && FLT_MANT_DIG == 24 && FLT_MAX_EXP == 128, "FIIR C float format changed");
_Static_assert(_Generic((LUCE_WATER_FREEZING_CELSIUS), int: 1, default: 0), "FIIR C constant LUCE_WATER_FREEZING_CELSIUS type changed");
_Static_assert(LUCE_WATER_FREEZING_CELSIUS == UINT64_C(0), "FIIR C constant LUCE_WATER_FREEZING_CELSIUS value changed");
_Static_assert(_Generic((LUCE_WATER_BOILING_CELSIUS), int: 1, default: 0), "FIIR C constant LUCE_WATER_BOILING_CELSIUS type changed");
_Static_assert(LUCE_WATER_BOILING_CELSIUS == UINT64_C(100), "FIIR C constant LUCE_WATER_BOILING_CELSIUS value changed");
_Static_assert(_Generic((LUCE_TEMPERATURE_DEFAULT_SCALE), luce_temperature_scale: 1, default: 0), "FIIR C constant LUCE_TEMPERATURE_DEFAULT_SCALE type changed");
_Static_assert(LUCE_TEMPERATURE_DEFAULT_SCALE == -INT64_C(2), "FIIR C constant LUCE_TEMPERATURE_DEFAULT_SCALE value changed");
_Static_assert(_Generic((LUCE_TEMPERATURE_OPEN_SCALE), luce_temperature_scale: 1, default: 0), "FIIR C constant LUCE_TEMPERATURE_OPEN_SCALE type changed");
_Static_assert(LUCE_TEMPERATURE_OPEN_SCALE == UINT64_C(7), "FIIR C constant LUCE_TEMPERATURE_OPEN_SCALE value changed");
_Static_assert(_Generic((LUCE_TEMPERATURE_SIGNED_MINIMUM), long long: 1, default: 0), "FIIR C constant LUCE_TEMPERATURE_SIGNED_MINIMUM type changed");
_Static_assert(LUCE_TEMPERATURE_SIGNED_MINIMUM == INT64_MIN, "FIIR C constant LUCE_TEMPERATURE_SIGNED_MINIMUM value changed");
_Static_assert(_Generic((LUCE_TEMPERATURE_UNSIGNED_MAXIMUM), unsigned long long: 1, default: 0), "FIIR C constant LUCE_TEMPERATURE_UNSIGNED_MAXIMUM type changed");
_Static_assert(LUCE_TEMPERATURE_UNSIGNED_MAXIMUM == UINT64_C(18446744073709551615), "FIIR C constant LUCE_TEMPERATURE_UNSIGNED_MAXIMUM value changed");
_Static_assert(_Generic((LUCE_TEMPERATURE_DEFAULT_ENABLED), _Bool: 1, default: 0), "FIIR C constant LUCE_TEMPERATURE_DEFAULT_ENABLED type changed");
_Static_assert(LUCE_TEMPERATURE_DEFAULT_ENABLED == 1, "FIIR C constant LUCE_TEMPERATURE_DEFAULT_ENABLED value changed");
_Static_assert(_Generic((LUCE_TEMPERATURE_HALF_STEP), luce_half_value: 1, default: 0), "FIIR C constant LUCE_TEMPERATURE_HALF_STEP type changed");
_Static_assert(LUCE_TEMPERATURE_HALF_STEP == (_Float16)(0.5), "FIIR C constant LUCE_TEMPERATURE_HALF_STEP value changed");
_Static_assert(_Generic((LUCE_TEMPERATURE_NEGATIVE_ZERO), float: 1, default: 0), "FIIR C constant LUCE_TEMPERATURE_NEGATIVE_ZERO type changed");
_Static_assert(LUCE_TEMPERATURE_NEGATIVE_ZERO == 0.0L && 1.0L / LUCE_TEMPERATURE_NEGATIVE_ZERO < 0.0L, "FIIR C constant LUCE_TEMPERATURE_NEGATIVE_ZERO value changed");
_Static_assert(_Generic((LUCE_TEMPERATURE_REFERENCE_RATIO), double: 1, default: 0), "FIIR C constant LUCE_TEMPERATURE_REFERENCE_RATIO type changed");
_Static_assert(LUCE_TEMPERATURE_REFERENCE_RATIO == 1.5, "FIIR C constant LUCE_TEMPERATURE_REFERENCE_RATIO value changed");
_Static_assert(_Generic((LUCE_TEMPERATURE_POSITIVE_INFINITY), double: 1, default: 0), "FIIR C constant LUCE_TEMPERATURE_POSITIVE_INFINITY type changed");
_Static_assert(__builtin_isinf(LUCE_TEMPERATURE_POSITIVE_INFINITY) && LUCE_TEMPERATURE_POSITIVE_INFINITY > 0.0L, "FIIR C constant LUCE_TEMPERATURE_POSITIVE_INFINITY value changed");
_Static_assert(_Generic((LUCE_TEMPERATURE_UNDEFINED), double: 1, default: 0), "FIIR C constant LUCE_TEMPERATURE_UNDEFINED type changed");
_Static_assert(__builtin_isnan(LUCE_TEMPERATURE_UNDEFINED), "FIIR C constant LUCE_TEMPERATURE_UNDEFINED value changed");
_Static_assert(_Generic((LUCE_TEMPERATURE_ABSOLUTE_ZERO), luce_degrees: 1, default: 0), "FIIR C constant LUCE_TEMPERATURE_ABSOLUTE_ZERO type changed");
_Static_assert(LUCE_TEMPERATURE_ABSOLUTE_ZERO == -INT64_C(273), "FIIR C constant LUCE_TEMPERATURE_ABSOLUTE_ZERO value changed");
_Static_assert(_Generic((LUCE_TEMPERATURE_SENSOR_LIMIT), unsigned long long: 1, default: 0), "FIIR C constant LUCE_TEMPERATURE_SENSOR_LIMIT type changed");
_Static_assert(LUCE_TEMPERATURE_SENSOR_LIMIT == UINT64_C(4095), "FIIR C constant LUCE_TEMPERATURE_SENSOR_LIMIT value changed");
_Static_assert(_Generic((LUCE_TEMPERATURE_MACRO_ENABLED), _Bool: 1, default: 0), "FIIR C constant LUCE_TEMPERATURE_MACRO_ENABLED type changed");
_Static_assert(LUCE_TEMPERATURE_MACRO_ENABLED == 1, "FIIR C constant LUCE_TEMPERATURE_MACRO_ENABLED value changed");
_Static_assert(_Generic((LUCE_TEMPERATURE_MACRO_HALF_STEP), luce_half_value: 1, default: 0), "FIIR C constant LUCE_TEMPERATURE_MACRO_HALF_STEP type changed");
_Static_assert(LUCE_TEMPERATURE_MACRO_HALF_STEP == (_Float16)(0.25), "FIIR C constant LUCE_TEMPERATURE_MACRO_HALF_STEP value changed");
_Static_assert(_Generic((LUCE_TEMPERATURE_MACRO_NEGATIVE_ZERO), float: 1, default: 0), "FIIR C constant LUCE_TEMPERATURE_MACRO_NEGATIVE_ZERO type changed");
_Static_assert(LUCE_TEMPERATURE_MACRO_NEGATIVE_ZERO == 0.0L && 1.0L / LUCE_TEMPERATURE_MACRO_NEGATIVE_ZERO < 0.0L, "FIIR C constant LUCE_TEMPERATURE_MACRO_NEGATIVE_ZERO value changed");
_Static_assert(_Generic((LUCE_TEMPERATURE_MACRO_REFERENCE_RATIO), double: 1, default: 0), "FIIR C constant LUCE_TEMPERATURE_MACRO_REFERENCE_RATIO type changed");
_Static_assert(LUCE_TEMPERATURE_MACRO_REFERENCE_RATIO == 1.25, "FIIR C constant LUCE_TEMPERATURE_MACRO_REFERENCE_RATIO value changed");
_Static_assert(_Generic((LUCE_TEMPERATURE_MACRO_POSITIVE_INFINITY), double: 1, default: 0), "FIIR C constant LUCE_TEMPERATURE_MACRO_POSITIVE_INFINITY type changed");
_Static_assert(__builtin_isinf(LUCE_TEMPERATURE_MACRO_POSITIVE_INFINITY) && LUCE_TEMPERATURE_MACRO_POSITIVE_INFINITY > 0.0L, "FIIR C constant LUCE_TEMPERATURE_MACRO_POSITIVE_INFINITY value changed");
_Static_assert(_Generic((LUCE_TEMPERATURE_MACRO_UNDEFINED), double: 1, default: 0), "FIIR C constant LUCE_TEMPERATURE_MACRO_UNDEFINED type changed");
_Static_assert(__builtin_isnan(LUCE_TEMPERATURE_MACRO_UNDEFINED), "FIIR C constant LUCE_TEMPERATURE_MACRO_UNDEFINED value changed");
_Static_assert(_Generic((LUCE_TEMPERATURE_MACRO_OPEN_SCALE), luce_temperature_scale: 1, default: 0), "FIIR C constant LUCE_TEMPERATURE_MACRO_OPEN_SCALE type changed");
_Static_assert(LUCE_TEMPERATURE_MACRO_OPEN_SCALE == UINT64_C(7), "FIIR C constant LUCE_TEMPERATURE_MACRO_OPEN_SCALE value changed");
_Static_assert(_Generic(&(luce_temperature_offset), volatile luce_degrees *: 1, default: 0), "FIIR C object luce_temperature_offset type or qualifiers changed");
_Static_assert(_Generic(&(luce_temperature_sensor_capacity), const unsigned long long *: 1, default: 0), "FIIR C object luce_temperature_sensor_capacity type or qualifiers changed");
_Static_assert(_Generic(&(luce_temperature_enabled), _Bool *: 1, default: 0), "FIIR C object luce_temperature_enabled type or qualifiers changed");
_Static_assert(_Generic(&(luce_temperature_ratio), double *: 1, default: 0), "FIIR C object luce_temperature_ratio type or qualifiers changed");
_Static_assert(_Generic(&(luce_temperature_unit), luce_temperature_scale *: 1, default: 0), "FIIR C object luce_temperature_unit type or qualifiers changed");

int64_t luce_fiir_temperature_read_luce_temperature_offset(void) {
    return (int64_t)(luce_temperature_offset);
}

int32_t luce_fiir_temperature_write_luce_temperature_offset(int64_t value) {
    if (value < -INT64_C(2147483648) || value > INT64_C(2147483647)) return INT32_C(0);
    luce_temperature_offset = (luce_degrees)value;
    return INT32_C(1);
}

uint64_t luce_fiir_temperature_read_luce_temperature_sensor_capacity(void) {
    return (uint64_t)(luce_temperature_sensor_capacity);
}

_Bool luce_fiir_temperature_read_luce_temperature_enabled(void) {
    return luce_temperature_enabled;
}

void luce_fiir_temperature_write_luce_temperature_enabled(_Bool value) {
    luce_temperature_enabled = (_Bool)value;
}

double luce_fiir_temperature_read_luce_temperature_ratio(void) {
    return luce_temperature_ratio;
}

void luce_fiir_temperature_write_luce_temperature_ratio(double value) {
    luce_temperature_ratio = (double)value;
}

int32_t luce_fiir_temperature_read_luce_temperature_unit(_Bool *result_is_negative, uint64_t *result_magnitude) {
    *result_is_negative = 0;
    *result_magnitude = UINT64_C(0);
    luce_temperature_scale luce_result = luce_temperature_unit;
    if (luce_result == LUCE_SCALE_CELSIUS) { *result_is_negative = 1; *result_magnitude = UINT64_C(2); }
    else if (luce_result == LUCE_SCALE_FAHRENHEIT) { *result_is_negative = 0; *result_magnitude = UINT64_C(42); }
    else return INT32_C(3);
    return INT32_C(1);
}

int32_t luce_fiir_temperature_write_luce_temperature_unit(_Bool value_is_negative, uint64_t value_magnitude) {
    luce_temperature_scale luce_native_value;
    if (value_is_negative && value_magnitude == UINT64_C(2)) luce_native_value = LUCE_SCALE_CELSIUS;
    else if (!value_is_negative && value_magnitude == UINT64_C(42)) luce_native_value = LUCE_SCALE_FAHRENHEIT;
    else return INT32_C(2);
    luce_temperature_unit = luce_native_value;
    return INT32_C(1);
}

double luce_fiir_temperature_luce_celsius_to_fahrenheit(double celsius) {
    return luce_celsius_to_fahrenheit(celsius);
}

float luce_fiir_temperature_luce_half_celsius(float celsius) {
    return luce_half_celsius(celsius);
}

float luce_fiir_temperature_luce_adjust_half(float value, float delta) {
    return (float)(luce_adjust_half((luce_half_value)value, (luce_half_value)delta));
}

int32_t luce_fiir_temperature_luce_adjust_celsius(int64_t celsius, int64_t delta, int64_t *result) {
    *result = 0;
    if (celsius < -INT64_C(2147483648) || celsius > INT64_C(2147483647)) return INT32_C(0);
    if (delta < -INT64_C(2147483648) || delta > INT64_C(2147483647)) return INT32_C(0);
    *result = (int64_t)(luce_adjust_celsius((int)celsius, (int)delta));
    return INT32_C(1);
}

int32_t luce_fiir_temperature_luce_echo_degrees(int64_t celsius, int64_t *result) {
    *result = 0;
    if (celsius < -INT64_C(2147483648) || celsius > INT64_C(2147483647)) return INT32_C(0);
    *result = (int64_t)(luce_echo_degrees((luce_degrees)celsius));
    return INT32_C(1);
}

int32_t luce_fiir_temperature_luce_echo_scale(_Bool scale_is_negative, uint64_t scale_magnitude, _Bool *result_is_negative, uint64_t *result_magnitude) {
    *result_is_negative = 0;
    *result_magnitude = UINT64_C(0);
    luce_temperature_scale luce_native_0;
    if (scale_is_negative && scale_magnitude == UINT64_C(2)) luce_native_0 = LUCE_SCALE_CELSIUS;
    else if (!scale_is_negative && scale_magnitude == UINT64_C(42)) luce_native_0 = LUCE_SCALE_FAHRENHEIT;
    else return INT32_C(2);
    luce_temperature_scale luce_result = luce_echo_scale((luce_temperature_scale)luce_native_0);
    if (luce_result == LUCE_SCALE_CELSIUS) { *result_is_negative = 1; *result_magnitude = UINT64_C(2); }
    else if (luce_result == LUCE_SCALE_FAHRENHEIT) { *result_is_negative = 0; *result_magnitude = UINT64_C(42); }
    else return INT32_C(3);
    return INT32_C(1);
}

int32_t luce_fiir_temperature_luce_invalid_scale(_Bool *result_is_negative, uint64_t *result_magnitude) {
    *result_is_negative = 0;
    *result_magnitude = UINT64_C(0);
    luce_temperature_scale luce_result = luce_invalid_scale();
    if (luce_result == LUCE_SCALE_CELSIUS) { *result_is_negative = 1; *result_magnitude = UINT64_C(2); }
    else if (luce_result == LUCE_SCALE_FAHRENHEIT) { *result_is_negative = 0; *result_magnitude = UINT64_C(42); }
    else return INT32_C(3);
    return INT32_C(1);
}

_Bool luce_fiir_temperature_luce_is_freezing(_Bool enabled, double celsius) {
    return luce_is_freezing(enabled, celsius);
}

int32_t luce_fiir_temperature_luce_shift_range(const struct __luce_fiir_temperature_record_luce_temperature_range *value, double delta, struct __luce_fiir_temperature_record_luce_temperature_range *result) {
    *result = (struct __luce_fiir_temperature_record_luce_temperature_range){0};
    luce_temperature_range luce_native_0;
    int32_t luce_native_0_status = __luce_fiir_temperature_decode_c_luce_temperature_range(value, &luce_native_0);
    if (luce_native_0_status != INT32_C(1)) return luce_native_0_status;
    luce_temperature_range luce_result = luce_shift_range(luce_native_0, delta);
    int32_t luce_result_status = __luce_fiir_temperature_encode_c_luce_temperature_range(result, &luce_result);
    if (luce_result_status != INT32_C(1)) return luce_result_status;
    return INT32_C(1);
}

int32_t luce_fiir_temperature_luce_shift_reading(const struct __luce_fiir_temperature_record_luce_temperature_reading *value, int64_t delta, struct __luce_fiir_temperature_record_luce_temperature_reading *result) {
    *result = (struct __luce_fiir_temperature_record_luce_temperature_reading){0};
    if (delta < -INT64_C(2147483648) || delta > INT64_C(2147483647)) return INT32_C(0);
    luce_temperature_reading luce_native_0;
    int32_t luce_native_0_status = __luce_fiir_temperature_decode_c_luce_temperature_reading(value, &luce_native_0);
    if (luce_native_0_status != INT32_C(1)) return luce_native_0_status;
    luce_temperature_reading luce_result = luce_shift_reading(luce_native_0, (luce_degrees)delta);
    int32_t luce_result_status = __luce_fiir_temperature_encode_c_luce_temperature_reading(result, &luce_result);
    if (luce_result_status != INT32_C(1)) return luce_result_status;
    return INT32_C(1);
}

int32_t luce_fiir_temperature_luce_temperature_sensor_open(int64_t value, void **result) {
    *result = 0;
    if (value < -INT64_C(2147483648) || value > INT64_C(2147483647)) return INT32_C(0);
    *result = (void *)(luce_temperature_sensor_open((luce_degrees)value));
    return INT32_C(1);
}

int32_t luce_fiir_temperature_luce_temperature_sensor_find(int64_t value, void **result) {
    *result = 0;
    if (value < -INT64_C(2147483648) || value > INT64_C(2147483647)) return INT32_C(0);
    *result = (void *)(luce_temperature_sensor_find((luce_degrees)value));
    return INT32_C(1);
}

int64_t luce_fiir_temperature_luce_temperature_sensor_value(void * sensor) {
    return (int64_t)(luce_temperature_sensor_value((luce_temperature_sensor *)sensor));
}

void * luce_fiir_temperature_luce_temperature_sensor_echo(void * sensor) {
    return (void *)(luce_temperature_sensor_echo((luce_temperature_sensor *)sensor));
}

_Bool luce_fiir_temperature_luce_temperature_sensor_present(void * sensor) {
    return luce_temperature_sensor_present((luce_temperature_sensor *)sensor);
}

int64_t luce_fiir_temperature_luce_temperature_sensor_validate(void * sensor) {
    return (int64_t)(luce_temperature_sensor_validate((luce_temperature_sensor *)sensor));
}

void luce_fiir_temperature_luce_temperature_sensor_close(void * sensor) {
    luce_temperature_sensor_close((luce_temperature_sensor *)sensor);
}

