#!/usr/bin/env python3
"""Stress the cycle collector with random object graphs. Deterministic for a seed.

Each generated Luce program builds and tears down a random graph of class objects: cycles
through optional fields, lists, maps, closures that capture objects, `Weak` back edges, a
child holding its parent, an `init` that fails after publishing `self` into its own fields,
and `deinit`s that read their fields. Links are cut by `clear()`, `remove`, `pop`,
`remove_at`, replacement and rebinding, so the collector's walks meet entries being let go
of. Every object's `deinit` prints its id and a bounded walk prints a checksum.

Each program runs in the interpreter and compiled four ways (native and C, each plain and
`--release`), twice: normally, and with `LUCE_CYCLE_STRESS=1`, where both runtimes collect
at every new candidate, so a collection happens at every release that could leave a cycle,
inside `clear`, `remove`, a `deinit` and a failed `init` included. The executions of one
mode must print the same thing; the two modes the same lines in some order (collection
timing moves `deinit`s and what a `Weak` answers, which the checksum leaves out); every run must end with status 0, which also proves
nothing was left alive (a leak exits 3). On macOS the compiled runs use MallocScribble, so
a use after free reads garbage; on Linux, with valgrind present, they run under memcheck.

Usage: tools/cycles_fuzz.py [--seed N] [--programs N] [--minutes M] [--gate]
Exit status is the number of findings, capped at 100.
"""
import os, random, subprocess, sys, time, pathlib, shutil, platform

root = pathlib.Path(__file__).resolve().parent.parent
os.chdir(root)
compiler = pathlib.Path(os.environ.get("LUCE_COMPILER", root / "build" / "luce"))
out = root / "build" / "cycles_fuzz"
out.mkdir(parents=True, exist_ok=True)
memcheck = shutil.which("valgrind") if platform.system() == "Linux" else None
modes = (("native", ["--native"]), ("native-release", ["--native", "--release"]),
         ("c", ["--backend=c"]), ("c-release", ["--backend=c", "--release"]))


def run(args, timeout, env=None):
    try:
        r = subprocess.run(args, capture_output=True, timeout=timeout, env=env)
        return r.returncode, r.stdout, r.stderr
    except subprocess.TimeoutExpired:
        return -1, b"", b"hang"


class Findings:
    def __init__(self):
        self.count = 0

    def report(self, kind, text, detail):
        self.count += 1
        path = out / f"finding_{self.count:03d}_{kind}.luc"
        path.write_text(text)
        print(f"FINDING {kind}: {detail}\n  input: {path}", flush=True)


PRELUDE = '''# generated by tools/cycles_fuzz.py
let bad = ErrorCode.package(1)

class Node:
    let id: int
    var next: Node? = none
    var items: list[Node] = []
    var table: map[int, Node] = {}
    var hook: (func() -> int)? = none
    var back: Weak[Node]? = none
    var owner: Panel? = none

    func init(self, id: int):
        self.id = id

    func deinit(self):
        var seen = self.items.length + self.table.length
        if self.next is not none:
            seen = seen + 1
        print(f"gone {self.id} {seen}")

class Panel:
    let id: int
    let child: Node
    var hook: func() -> int

    func init(self, id: int, fail: bool) -> unit!:
        self.id = id
        self.child = Node(id + 100000)
        self.hook = func () -> int:
            return self.id
        self.child.owner = self
        if fail:
            error(bad, "no room")

    func deinit(self):
        print(f"gone panel {self.id}")

func walk(n: Node?, depth: int) -> int:
    let node = n else return 0
    if depth == 0:
        return node.id
    var total = node.id * 3 + walk(node.next, depth - 1)
    for item in node.items:
        total = (total + walk(item, depth - 1)) % 1000003
    for key in node.table.keys():
        total = (total + key + walk(node.table[key], depth - 1)) % 1000003
    if let h = node.hook:
        total = total + h()
    if let b = node.back:
        # whether a weak target is still alive depends on when collections run, which the
        # stress mode moves; `get` is exercised, its answer kept out of the output
        if let p = b.get():
            discard(p.id)
        total = total + 1
    if let o = node.owner:
        total = total + o.hook()
    return total % 1000003
'''


class Generator:
    def __init__(self, rng):
        self.rng = rng
        self.ids = 0
        self.slots = rng.randint(3, 7)
        self.panels = 0

    def fresh(self):
        self.ids += 1
        return self.ids

    def slot(self):
        return f"v{self.rng.randrange(self.slots)}"

    def pair(self, body, pad):
        a, b = self.slot(), self.slot()
        return [f"{pad}if let a = {a}:", f"{pad}    if let b = {b}:"] + [f"{pad}        {line}" for line in body]

    def one(self, a_only, pad):
        a = self.slot()
        return [f"{pad}if let a = {a}:"] + [f"{pad}    {line}" for line in a_only]

    def step(self, pad, depth):
        r = self.rng
        k = r.randint(0, 20)
        if k <= 2:
            return [f"{pad}{self.slot()} = Node({self.fresh()})"]
        if k == 3:
            return self.pair(["a.next = b"], pad)
        if k == 4:
            return self.pair(["a.items.append(b)"], pad)
        if k == 5:
            return self.pair([f"a.table[{r.randint(0, 4)}] = b"], pad)
        if k == 6:
            return self.pair(["a.hook = func () -> int:", "    return b.id"], pad)
        if k == 7:
            return self.pair(["a.back = Weak(b)"], pad)
        if k == 8:
            return self.one([r.choice(["a.items.clear()", "a.table.clear()", "a.next = none", "a.hook = none", "a.owner = none"])], pad)
        if k == 9:
            return self.one([f"discard(a.table.remove({r.randint(0, 4)}))"], pad)
        if k == 10:
            return self.one(["if a.items.length > 0:", "    discard(a.items.pop())"], pad)
        if k == 11:
            return self.one(["if a.items.length > 0:", "    discard(a.items.remove_at(0))"], pad)
        if k == 12:
            return [f"{pad}{self.slot()} = none"]
        if k == 13:
            return [f"{pad}{self.slot()} = {self.slot()}"]
        if k == 14:
            return [f"{pad}print(\"walk\", walk({self.slot()}, {r.randint(1, 3)}))"]
        if k == 15:
            self.panels += 1
            name = f"p{self.panels}"
            return [f"{pad}let {name}: Panel? = Panel({self.fresh()}, true) catch failure:",
                    f"{pad}    print(\"failed\", failure.message)",
                    f"{pad}    recover none",
                    f"{pad}print({name} is none)"]
        if k == 16:
            self.panels += 1
            name = f"p{self.panels}"
            lines = [f"{pad}let {name} = try Panel({self.fresh()}, false)"]
            lines += self.one([f"a.owner = {name}", f"{name}.child.next = a"], pad)
            return lines
        if k == 17 and depth > 0:
            self.loops = getattr(self, "loops", 0) + 1
            lines = [f"{pad}for i{self.loops} in 0..<{r.randint(1, 4)}:"]
            for _ in range(r.randint(1, 3)):
                lines += self.step(pad + "    ", depth - 1)
            return lines
        if k == 18 and depth > 0:
            # a scope of its own: its cycle is garbage once it ends
            self.scopes = getattr(self, "scopes", 0) + 1
            s_, t_ = f"s{self.scopes}", f"t{self.scopes}"
            lines = [f"{pad}if true:", f"{pad}    let {s_} = Node({self.fresh()})", f"{pad}    let {t_} = Node({self.fresh()})",
                     f"{pad}    {s_}.next = {t_}", f"{pad}    {t_}.items.append({s_})"]
            for _ in range(r.randint(0, 2)):
                lines += self.step(pad + "    ", depth - 1)
            return lines
        if k == 19:
            return self.one(["a.items.append(a)", "a.table[9] = a"], pad)
        return self.pair(["a.items = [b, a]", "b.table = {1: a}"], pad)

    def program(self):
        lines = PRELUDE.split("\n")
        lines += ["pub func main(arguments: list[str]) -> int!:", "    discard(arguments)"]
        for i in range(self.slots):
            lines.append(f"    var v{i}: Node? = Node({self.fresh()})")
        for _ in range(self.rng.randint(8, 40)):
            lines += self.step("    ", 2)
        for i in range(self.slots):
            lines.append(f"    print(\"end\", walk(v{i}, 2))")
        lines.append("    return 0")
        return "\n".join(lines) + "\n"


def execute(exe, stress, timeout):
    env = dict(os.environ)
    if stress:
        env["LUCE_CYCLE_STRESS"] = "1"
    if platform.system() == "Darwin":
        env["MallocScribble"] = "1"
        env["MallocNanoZone"] = "0"
    args = [str(exe)]
    if memcheck:
        args = [memcheck, "--error-exitcode=99", "--leak-check=no", "--max-stackframe=8388608", "-q"] + args
    return run(args, timeout, env)


def check(text, findings, label, timeout):
    path = out / "generated.luc"
    path.write_text(text)
    outputs = {}
    for stress in (False, True):
        env = dict(os.environ)
        if stress:
            env["LUCE_CYCLE_STRESS"] = "1"
        tag = "stress" if stress else "plain"
        status, so, se = run([str(compiler), "run", str(path)], timeout, env)
        if status != 0:
            findings.report(f"interpreter-{tag}", text, f"{label}: the interpreter ({tag}) stopped with {status}: {se.decode('utf-8', 'replace')[-300:]!r}")
            return
        outputs[("interpreter", tag)] = so
    for name, flags in modes:
        exe = out / f"generated-{name}"
        status, so, se = run([str(compiler), "build", str(path), *flags, "-o", str(exe)], timeout * 6)
        if status != 0:
            findings.report(f"build-{name}", text, f"{label}: the build ({name}) failed: {(so + se).decode('utf-8', 'replace')[-300:]!r}")
            return
        for stress in (False, True):
            tag = "stress" if stress else "plain"
            status, so, se = execute(exe, stress, timeout * (8 if memcheck else 1))
            if status != 0:
                findings.report(f"run-{name}-{tag}", text, f"{label}: {name} ({tag}) stopped with {status}: {se.decode('utf-8', 'replace')[-300:]!r}")
                return
            outputs[(name, tag)] = so
    for tag in ("plain", "stress"):
        seen = {k[0]: v for k, v in outputs.items() if k[1] == tag}
        if len(set(seen.values())) > 1:
            first = seen["interpreter"]
            odd = [k for k, v in seen.items() if v != first]
            findings.report(f"disagree-{tag}", text, f"{label}: {tag} runs disagree with the interpreter: {odd}")
            return
    plain = sorted(outputs[("interpreter", "plain")].splitlines())
    stress = sorted(outputs[("interpreter", "stress")].splitlines())
    if plain != stress:
        findings.report("stress-lines", text, f"{label}: stress mode printed different lines, not only reordered deinits")


def main():
    args = sys.argv[1:]
    seed, programs, minutes = 1, 20, 0.0
    i = 0
    while i < len(args):
        a = args[i]
        if a == "--seed":
            seed = int(args[i + 1]); i += 1
        elif a == "--programs":
            programs = int(args[i + 1]); i += 1
        elif a == "--minutes":
            minutes = float(args[i + 1]); i += 1
        elif a == "--gate":
            seed, programs = 11, 6
        i += 1
    if not compiler.exists():
        print(f"cycles_fuzz: no compiler at {compiler}")
        return 1
    rng = random.Random(seed)
    findings = Findings()
    start = time.time()
    n = 0
    while True:
        if minutes > 0:
            if time.time() - start > minutes * 60:
                break
        elif n >= programs:
            break
        text = Generator(rng).program()
        check(text, findings, f"program {n} (seed {seed})", 60)
        n += 1
    print(f"cycles_fuzz: {n} programs, {findings.count} findings (seed {seed}{', valgrind' if memcheck else ''})")
    return min(findings.count, 100)


if __name__ == "__main__":
    sys.exit(main())
