#!/usr/bin/env python3
"""Embed the readable Luce prelude; --check verifies it without writing."""
import argparse
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
source = (root / "rt/prelude.luc").read_text()
literal = source.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
text = ("## Generated by tools/embed_prelude.py; edit rt/prelude.luc.\n"
        f'pub let source: str = "{literal}"\n')
target = root / "src/support/prelude.lucb"
if args.check:
    if not target.exists() or target.read_text() != text:
        raise SystemExit("embedded prelude is stale; run tools/embed_prelude.py")
else:
    target.write_text(text)
