#!/usr/bin/env python3
"""Write src/support/version.lucb from VERSION, the one place the version lives; build.sh
runs this first. With `--check`, write nothing: exit 1 when the embedded text is not VERSION."""
import pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from generated import header

root = pathlib.Path(__file__).resolve().parent.parent
version = (root / "VERSION").read_text(encoding="utf-8").strip()
target = root / "src" / "support" / "version.lucb"
text = header("version", "The Luce version", "Generated by tools/embed_version.py from VERSION; edit that file, not this one.") + f"## The version of Luce this binary was built from.\npub let text: str = \"{version}\"\n"
if "--check" in sys.argv:
    if target.read_text(encoding="utf-8") != text:
        print("src/support/version.lucb is not VERSION; run tools/embed_version.py")
        sys.exit(1)
    sys.exit(0)
if target.exists() and target.read_text(encoding="utf-8") == text:
    sys.exit(0)
target.write_bytes((text).encode("utf-8"))
print(f"wrote src/support/version.lucb ({version})")
