#!/usr/bin/env python3
"""Write src/support/runtime.lucb: the runtime's Base sources under rt/ as text, so the
compiler carries the runtime and drops it into the package it emits. build.sh runs this
first. With `--check`, write nothing: exit 1 when the embedded text is stale."""
import pathlib, sys

root = pathlib.Path(__file__).resolve().parent.parent
target = root / "src" / "support" / "runtime.lucb"
files = sorted((root / "rt").glob("*.lucb"))

def literal(text):
    out = text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return '"' + out + '"'

lines = ["## Generated by tools/embed_runtime.py from rt/*.lucb; edit those files, not this one.", ""]
lines.append(f"pub let count: usize = {len(files)}")
lines.append(f"pub let names: str[{len(files)}] = [" + ", ".join(literal(f.name) for f in files) + "]")
lines.append(f"pub let sources: str[{len(files)}] = [")
for i, f in enumerate(files):
    comma = "," if i + 1 < len(files) else ""
    lines.append("    " + literal(f.read_text()) + comma)
lines.append("]")
text = "\n".join(lines) + "\n"
if "--check" in sys.argv:
    if not target.exists() or target.read_text() != text:
        print("src/support/runtime.lucb is stale; run tools/embed_runtime.py")
        sys.exit(1)
    sys.exit(0)
target.write_text(text)
print(f"wrote src/support/runtime.lucb ({len(files)} files)")
