#!/usr/bin/env python3
"""Write src/support/runtime.lucb: the runtime's Base sources under rt/ as text, so the
compiler carries the runtime and drops it into the package it emits. build.sh runs this
first. With `--check`, write nothing: exit 1 when the embedded text is stale."""
import pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from generated import header

root = pathlib.Path(__file__).resolve().parent.parent
target = root / "src" / "support" / "runtime.lucb"
# the kernel is a directory module (its ORDER and fragments); number_text is the one module
# the compiler shares with the programs it emits, kept once under src/support
files = sorted(p for p in (root / "rt").rglob("*") if p.is_file() and (p.suffix == ".lucb" or p.name == "ORDER"))
sources = [(f.relative_to(root / "rt").as_posix(), f) for f in files]
sources.append(("number_text.lucb", root / "src" / "support" / "number_text.lucb"))

def literal(text):
    out = text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return '"' + out + '"'

lines = [header("runtime", "The runtime Luce programs link", "Generated by tools/embed_runtime.py from rt/ and src/support/number_text.lucb; edit those files, not this one.").rstrip("\n")]
lines.append("## How many runtime sources there are.")
lines.append(f"pub let count: usize = {len(sources)}")
lines.append("## Each source's path under the runtime's directory, `kernel/ORDER` and the like.")
lines.append(f"pub let names: str[{len(sources)}] = [" + ", ".join(literal(name) for name, _ in sources) + "]")
lines.append("## Each source's text, in the order of `names`.")
lines.append(f"pub let sources: str[{len(sources)}] = [")
for i, (_, f) in enumerate(sources):
    comma = "," if i + 1 < len(sources) else ""
    lines.append("    " + literal(f.read_text(encoding="utf-8")) + comma)
lines.append("]")
text = "\n".join(lines) + "\n"
if "--check" in sys.argv:
    if not target.exists() or target.read_text(encoding="utf-8") != text:
        print("src/support/runtime.lucb is stale; run tools/embed_runtime.py")
        sys.exit(1)
    sys.exit(0)
target.write_bytes((text).encode("utf-8"))
print(f"wrote src/support/runtime.lucb ({len(sources)} files)")
