#!/usr/bin/env python3
"""Embed the readable Luce prelude; --check verifies it without writing."""
import argparse
import pathlib
import sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from generated import header

root = pathlib.Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
source = (root / "rt/prelude.luc").read_text(encoding="utf-8")
literal = source.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
text = (header("prelude", "What every Luce module sees without an import", "Generated by tools/embed_prelude.py from rt/prelude.luc; edit that file, not this one.")
        + "## The prelude's Luce source.\n"
        + f'pub let source: str = "{literal}"\n')
target = root / "src/support/prelude.lucb"
if args.check:
    if not target.exists() or target.read_text(encoding="utf-8") != text:
        raise SystemExit("embedded prelude is stale; run tools/embed_prelude.py")
else:
    target.write_bytes((text).encode("utf-8"))
