#!/usr/bin/env python3
"""Write src/support/toolchain_build.lucb for the Base compiler BASE that is about to build
Luce: the version it reports, which every luce-base this Luce runs must report too, and
its absolute path, where a development build finds it when no luce-base is laid out
beside it (support/toolchain.lucb). build.sh and tools/build_windows.py run this; the file
belongs to the build, not to the repository.

Usage: tools/embed_toolchain.py BASE
"""
import pathlib, subprocess, sys

root = pathlib.Path(__file__).resolve().parent.parent
if len(sys.argv) != 2:
    sys.exit(__doc__)
base = pathlib.Path(sys.argv[1]).resolve()
answer = subprocess.run([str(base), "--version"], capture_output=True, text=True)
version = answer.stdout.strip()
if answer.returncode != 0 or not version.startswith("luce-base "):
    sys.exit(f"embed_toolchain: {base} --version answered {answer.returncode}: {version!r} {answer.stderr.strip()!r}")


def literal(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


target = root / "src" / "support" / "toolchain_build.lucb"
target.write_text(
    "## Generated by tools/embed_toolchain.py when Luce is built: the Base compiler it was built\n"
    "## with. Not in the repository.\n\n"
    "## What that compiler's `--version` says; every luce-base this Luce runs must say the same.\n"
    f"pub let base_version: str = {literal(version)}\n\n"
    "## Where it was, the last place this Luce looks for a luce-base before the path.\n"
    f"pub let base_path: str = {literal(str(base))}\n", encoding="utf-8")
print(f"wrote src/support/toolchain_build.lucb ({version}, {base})")
